# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(default=b'Empty Field', max_length=250)),
                ('title', models.CharField(default=b'Empty Field', max_length=250)),
                ('description', models.CharField(default=b'Empty Field', max_length=250)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('image_url', models.URLField(max_length=250)),
                ('image_mobile_ready', models.BooleanField(default=False)),
            ],
        ),
    ]
