# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileapi',
            name='cache_key',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mobileapi',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mobileapi',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
