# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20170305_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileapi',
            name='cache_key',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mobileapi',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mobileapi',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
